instructions updated
breatheco-de/exercise-todo-list-cli-python pull request #9
Opened 2021-03-25 18:44 UTC by ElviraQDP

review

2021-03-30 14:52 UTC, mortegac requested changes
Falta agregar
```
💡 Important: Remember to create a new repository, update the remote (`git remote set-url origin <your new url>`), and upload the code to your new repository using `add`, `commit` and `push`.
```




Falta agregar la versión en español.  Agrégalo a este Pull request, por favor

2021-05-10 20:18 UTC, mortegac requested changes
revisar imagen no disponible

2021-05-10 20:18 UTC, mortegac commented on README.es.md
> +- Tu aplicación debe funcionar desde la terminal [como esta] (https://projects.breatheco.de/json?slug=todo-list-cli&preview).
La imagen no existe.  Devuelve un 404

2021-05-11 20:22 UTC, ElviraQDP commented on README.es.md
> +- Tu aplicación debe funcionar desde la terminal [como esta] (https://projects.breatheco.de/json?slug=todo-list-cli&preview).
@alesanchezr do you remember what image is missing here?

2021-05-11 20:23 UTC, merged